import { Grant } from "./types";

// 기업마당(bizinfo.go.kr) 실제 공고 데이터 — 2026년 4월 기준
// URL: https://www.bizinfo.go.kr/web/lay1/bbs/S1T122C128/AS/74/view.do?pblancId={id}
const BIZINFO_DETAIL = "https://www.bizinfo.go.kr/web/lay1/bbs/S1T122C128/AS/74/view.do?pblancId=";

export const grants: Grant[] = [
  // ──────── 창업 / AI / IT ────────
  {
    id: "PBLN_000000000120374",
    title: "2026년 과학기술정보통신부 GovTech 창업기업 AI 실증·사업화 지원사업 모집 공고",
    orgName: "과학기술정보통신부",
    category: "창업",
    region: "전국",
    targetBizTypes: ["IT·소프트웨어", "서비스업"],
    amount: "공고 확인",
    deadline: "2026-04-23",
    description: "GovTech 분야 창업기업의 AI 기술 실증 및 사업화를 지원하는 사업. 공공 분야 AI 서비스 개발·실증 지원.",
    requirements: "AI 기술 기반 GovTech 분야 창업기업. 공공 서비스 혁신 AI 솔루션 보유 기업.",
    url: BIZINFO_DETAIL + "PBLN_000000000120374",
  },
  {
    id: "PBLN_000000000120373",
    title: "2026년 SaaS 개발·사업화 지원 사업 공고",
    orgName: "과학기술정보통신부",
    category: "기술",
    region: "전국",
    targetBizTypes: ["IT·소프트웨어"],
    amount: "공고 확인",
    deadline: "2026-04-22",
    description: "SaaS(Software as a Service) 제품 개발 및 사업화를 지원하는 사업. 클라우드 기반 소프트웨어 서비스 개발 지원.",
    requirements: "SaaS 제품 개발 역량을 보유한 중소·스타트업 기업.",
    url: BIZINFO_DETAIL + "PBLN_000000000120373",
  },
  {
    id: "PBLN_000000000120379",
    title: "2026년 온디바이스 AI 서비스 실증·확산 사업 공고",
    orgName: "과학기술정보통신부",
    category: "기술",
    region: "전국",
    targetBizTypes: ["IT·소프트웨어", "제조"],
    amount: "공고 확인",
    deadline: "2026-04-30",
    description: "온디바이스 AI 기술을 활용한 서비스 실증 및 확산을 지원. 엣지 AI, 모바일 AI 등 디바이스 탑재 AI 서비스 개발.",
    requirements: "온디바이스 AI 기술 보유 기업. 실증 가능한 서비스 모델 보유.",
    url: BIZINFO_DETAIL + "PBLN_000000000120379",
  },
  {
    id: "PBLN_000000000120382",
    title: "2026년 고성능 컴퓨팅 지원 사용자 모집 공고",
    orgName: "정보통신산업진흥원",
    category: "기술",
    region: "전국",
    targetBizTypes: ["IT·소프트웨어", "제조", "서비스업"],
    amount: "GPU/NPU 서버 자원 지원",
    deadline: "2026-04-23",
    description: "AI 개발·추론에 필수적인 컴퓨팅 자원 및 개발 환경 제공. GPU(A100, H100/H200) 및 NPU 서버 지원.",
    requirements: "국내 중소·벤처기업, 스타트업(창업 7년 이내), 산업체. NPU는 대학·병원도 가능.",
    url: BIZINFO_DETAIL + "PBLN_000000000120382",
  },
  {
    id: "PBLN_000000000120368",
    title: "AI 응용제품 신속 상용화(보건분야·디지털 의료기기) 지원사업",
    orgName: "보건복지부",
    category: "기술",
    region: "전국",
    targetBizTypes: ["IT·소프트웨어", "제조"],
    amount: "공고 확인",
    deadline: "2026-04-24",
    description: "보건 분야 AI 응용제품 및 디지털 의료기기의 신속 상용화를 지원하는 사업.",
    requirements: "AI 기반 보건·의료 분야 제품 개발 기업.",
    url: BIZINFO_DETAIL + "PBLN_000000000120368",
  },
  {
    id: "PBLN_000000000120348",
    title: "[서울] 2026년 서울-바젤 스타트업 허브 액셀러레이션 프로그램 참여기업 모집 공고",
    orgName: "한국과학기술연구원",
    category: "창업",
    region: "서울",
    targetBizTypes: ["IT·소프트웨어", "제조", "서비스업"],
    amount: "액셀러레이팅 프로그램 지원",
    deadline: "2026-04-15",
    description: "서울과 바젤을 연계한 글로벌 스타트업 액셀러레이션 프로그램. 해외 진출 지원 및 멘토링 제공.",
    requirements: "서울 소재 스타트업. 글로벌 진출 의향이 있는 기업.",
    url: BIZINFO_DETAIL + "PBLN_000000000120348",
  },
  {
    id: "PBLN_000000000120346",
    title: "2026년 화성시 와우메이커스 WoW! Makers 시제품 제작지원사업 예비창업자·스타트업 모집 공고",
    orgName: "화성산업진흥원",
    category: "창업",
    region: "경기",
    targetBizTypes: ["IT·소프트웨어", "제조", "서비스업", "기타"],
    amount: "시제품 제작 지원",
    deadline: "2026-04-17",
    description: "예비창업자 및 스타트업의 시제품 제작을 지원하는 사업. 아이디어 구현을 위한 시제품 개발 비용 지원.",
    requirements: "예비창업자 또는 스타트업(창업 7년 이내). 화성시 소재 또는 화성시 관련 사업.",
    url: BIZINFO_DETAIL + "PBLN_000000000120346",
  },
  {
    id: "PBLN_000000000120345",
    title: "2026년 만화웹툰분야 창업기업 육성지원(초기기업) 공고",
    orgName: "한국콘텐츠진흥원",
    category: "창업",
    region: "전국",
    targetBizTypes: ["IT·소프트웨어", "서비스업"],
    amount: "공고 확인",
    deadline: "2026-04-09",
    description: "만화·웹툰 분야 초기 창업기업 육성을 위한 지원사업. 콘텐츠 개발 및 사업화 지원.",
    requirements: "만화·웹툰 분야 창업 3년 이내 초기기업.",
    url: BIZINFO_DETAIL + "PBLN_000000000120345",
  },
  {
    id: "PBLN_000000000120344",
    title: "2026년 만화웹툰분야 창업기업 육성지원(예비기업) 공고",
    orgName: "한국콘텐츠진흥원",
    category: "창업",
    region: "전국",
    targetBizTypes: ["IT·소프트웨어", "서비스업"],
    amount: "공고 확인",
    deadline: "2026-04-09",
    description: "만화·웹툰 분야 예비 창업기업 육성 지원. 예비창업자의 사업 아이디어 구체화 및 창업 지원.",
    requirements: "만화·웹툰 분야 예비창업자. 사업 아이디어 보유자.",
    url: BIZINFO_DETAIL + "PBLN_000000000120344",
  },
  {
    id: "PBLN_000000000120331",
    title: "[전남] 강진군 기후테크 스타트업 육성사업 해커톤 대회 참가팀 모집 공고",
    orgName: "전라남도환경산업진흥원",
    category: "창업",
    region: "전남",
    targetBizTypes: ["IT·소프트웨어", "제조", "기타"],
    amount: "해커톤 상금 및 사업화 지원",
    deadline: "2026-04-23",
    description: "기후테크 분야 스타트업 육성을 위한 해커톤 대회. 환경·기후 관련 혁신 기술 아이디어 발굴.",
    requirements: "기후테크 분야 스타트업 또는 예비창업팀.",
    url: BIZINFO_DETAIL + "PBLN_000000000120331",
  },

  // ──────── 소상공인 / 경영 ────────
  {
    id: "PBLN_000000000120387",
    title: "[울산] 2026년 소상공인 고용보험료 지원사업 공고",
    orgName: "울산경제일자리진흥원",
    category: "고용",
    region: "울산",
    targetBizTypes: ["음식점·외식", "소매·유통", "서비스업", "기타"],
    max_employees: 10,
    amount: "고용보험료 15~30% 지원",
    deadline: "2026-12-10",
    description: "소상공인 자영업자의 고용보험 가입 장려 및 보험료 부담 경감. 등급별 15~30% 보험료 지원, 최소 본인 부담 5%.",
    requirements: "울산 소재 소상공인 자영업자. 자영업자 고용보험 가입자.",
    url: BIZINFO_DETAIL + "PBLN_000000000120387",
  },
  {
    id: "PBLN_000000000120353",
    title: "[강원] 속초시 2026년 소상공인 시설개선 지원사업 모집 공고",
    orgName: "강원특별자치도경제진흥원",
    category: "경영",
    region: "강원",
    targetBizTypes: ["음식점·외식", "소매·유통", "서비스업"],
    amount: "시설개선 비용 지원",
    deadline: "2026-04-21",
    description: "속초시 소재 소상공인의 영업장 시설개선을 지원하는 사업. 노후 시설 교체, 환경 개선 등.",
    requirements: "속초시 소재 소상공인. 영업장 시설개선이 필요한 업체.",
    url: BIZINFO_DETAIL + "PBLN_000000000120353",
  },
  {
    id: "PBLN_000000000120359",
    title: "[경기] 2026년 1차 음식점 미세먼지·악취 방지시설 설치 지원사업 공고",
    orgName: "경기환경에너지진흥원",
    category: "경영",
    region: "경기",
    targetBizTypes: ["음식점·외식"],
    amount: "방지시설 설치비 지원",
    deadline: "2026-04-17",
    description: "경기도 음식점의 미세먼지 및 악취 방지시설 설치를 지원. 영업장 환경 개선.",
    requirements: "경기도 소재 음식점 영업자.",
    url: BIZINFO_DETAIL + "PBLN_000000000120359",
  },
  {
    id: "PBLN_000000000120349",
    title: "[경기] 북부 2026년 기업 통합 지원 프로그램 기새든든 참여기업 모집 공고",
    orgName: "경기도일자리재단",
    category: "경영",
    region: "경기",
    targetBizTypes: ["IT·소프트웨어", "제조", "서비스업", "기타"],
    amount: "통합 경영 지원",
    deadline: "2026-04-16",
    description: "경기 북부 지역 기업을 위한 통합 지원 프로그램. 경영, 마케팅, 인력 등 맞춤형 지원.",
    requirements: "경기 북부 지역 소재 중소기업.",
    url: BIZINFO_DETAIL + "PBLN_000000000120349",
  },
  {
    id: "PBLN_000000000120342",
    title: "2026년 기업승계 M&A 활성화를 위한 컨설팅 지원사업 시행계획 공고",
    orgName: "기술보증기금",
    category: "경영",
    region: "전국",
    targetBizTypes: ["제조", "IT·소프트웨어", "서비스업", "기타"],
    amount: "컨설팅 비용 지원",
    deadline: "상시",
    description: "기업승계 및 M&A 활성화를 위한 전문 컨설팅 지원. 기업 가치평가, 매칭, 법률·세무 자문 등.",
    requirements: "기업승계 또는 M&A를 고려 중인 중소기업.",
    url: BIZINFO_DETAIL + "PBLN_000000000120342",
  },

  // ──────── 투자 / 금융 ────────
  {
    id: "PBLN_000000000120381",
    title: "2026년 전문 투자기관 연계형 투자유치 지원사업 지원기업 모집 공고",
    orgName: "한국보건산업진흥원",
    category: "금융",
    region: "전국",
    targetBizTypes: ["IT·소프트웨어", "제조"],
    amount: "투자유치 역량 강화 지원",
    deadline: "2026-04-14",
    description: "바이오헬스 분야 스타트업의 투자유치 역량 강화 지원. 교육, 컨설팅, 네트워킹, 투자 연계 기회 제공.",
    requirements: "바이오헬스 분야 기술 보유 스타트업.",
    url: BIZINFO_DETAIL + "PBLN_000000000120381",
  },
  {
    id: "PBLN_000000000120362",
    title: "2026년 친환경차 보급촉진을 위한 이차보전 사업 공고",
    orgName: "산업통상자원부",
    category: "금융",
    region: "전국",
    targetBizTypes: ["제조", "서비스업"],
    amount: "이차보전(금리지원)",
    deadline: "2026-04-27",
    description: "친환경차 보급 확대를 위한 이차보전(금리 차이 보전) 지원 사업.",
    requirements: "친환경차 관련 제조·서비스 기업.",
    url: BIZINFO_DETAIL + "PBLN_000000000120362",
  },
  {
    id: "PBLN_000000000120355",
    title: "2026년 3차 미래환경산업육성융자(오염방지시설자금) 지원사업 공고",
    orgName: "한국환경산업기술원",
    category: "금융",
    region: "전국",
    targetBizTypes: ["제조", "서비스업", "기타"],
    amount: "융자(대출) 지원",
    deadline: "2026-10-30",
    description: "환경 산업 육성을 위한 오염방지시설 설치 자금 융자 지원 사업.",
    requirements: "오염방지시설 설치가 필요한 중소기업.",
    url: BIZINFO_DETAIL + "PBLN_000000000120355",
  },

  // ──────── 수출 / 해외진출 ────────
  {
    id: "PBLN_000000000120371",
    title: "2026년 로봇분야 해외인증 획득비용 지원사업 모집 공고",
    orgName: "산업통상자원부",
    category: "수출",
    region: "전국",
    targetBizTypes: ["제조", "IT·소프트웨어"],
    amount: "해외인증 비용 지원",
    deadline: "2026-04-23",
    description: "로봇 분야 중소기업의 해외 인증 획득을 위한 비용 지원. 수출 경쟁력 강화.",
    requirements: "로봇 분야 제품 보유 중소기업. 해외 인증이 필요한 기업.",
    url: BIZINFO_DETAIL + "PBLN_000000000120371",
  },
  {
    id: "PBLN_000000000120369",
    title: "[강원] 2026년 1차 강원특별자치도 수출기업 해외 물류비 지원사업",
    orgName: "강원특별자치도",
    category: "수출",
    region: "강원",
    targetBizTypes: ["제조", "농림수산", "기타"],
    amount: "해외 물류비 지원",
    deadline: "2026-04-10",
    description: "강원도 수출기업의 해외 물류비 부담 경감을 위한 지원 사업.",
    requirements: "강원특별자치도 소재 수출 중소기업.",
    url: BIZINFO_DETAIL + "PBLN_000000000120369",
  },
  {
    id: "PBLN_000000000120367",
    title: "[경남] 2026년 소비재 중소기업 해외유통망 진출 지원사업",
    orgName: "경상남도",
    category: "수출",
    region: "경남",
    targetBizTypes: ["제조", "소매·유통"],
    amount: "해외유통망 진출 지원",
    deadline: "2026-04-24",
    description: "경남 소재 소비재 중소기업의 해외 유통망 진출을 지원하는 사업.",
    requirements: "경상남도 소재 소비재 분야 중소기업.",
    url: BIZINFO_DETAIL + "PBLN_000000000120367",
  },
  {
    id: "PBLN_000000000120303",
    title: "[강원] 2026년 수출 보험료 지원공고",
    orgName: "한국무역보험공사",
    category: "수출",
    region: "강원",
    targetBizTypes: ["제조", "IT·소프트웨어", "농림수산", "기타"],
    amount: "수출 보험료 지원",
    deadline: "상시",
    description: "강원 지역 수출기업의 수출 보험료 부담을 경감하기 위한 지원 사업.",
    requirements: "강원 소재 수출 중소기업.",
    url: BIZINFO_DETAIL + "PBLN_000000000120303",
  },
  {
    id: "PBLN_000000000120389",
    title: "[경기] 시흥시 2026년 시흥산업진흥원 수출입 컨설팅 운영 공고",
    orgName: "시흥산업진흥원",
    category: "수출",
    region: "경기",
    targetBizTypes: ["제조", "IT·소프트웨어", "기타"],
    amount: "수출입 컨설팅 지원",
    deadline: "상시",
    description: "시흥시 소재 기업의 수출입 역량 강화를 위한 전문 컨설팅 운영.",
    requirements: "시흥시 소재 수출입 기업.",
    url: BIZINFO_DETAIL + "PBLN_000000000120389",
  },

  // ──────── 인력 / 고용 ────────
  {
    id: "PBLN_000000000120375",
    title: "2026년 중소기업 연구인력 현장맞춤형 양성지원사업 연구인력(R&D) 양성프로그램 참여기업 모집 공고",
    orgName: "경기벤처기업협회",
    category: "인력",
    region: "경기",
    targetBizTypes: ["IT·소프트웨어", "제조"],
    amount: "R&D 인력 양성 지원",
    deadline: "상시",
    description: "중소기업의 R&D 인력 양성을 위한 현장 맞춤형 프로그램. 연구개발 역량 강화.",
    requirements: "경기 소재 중소기업. R&D 인력 양성이 필요한 기업.",
    url: BIZINFO_DETAIL + "PBLN_000000000120375",
  },
  {
    id: "PBLN_000000000120388",
    title: "[울산] 2026년 자동차 부품업종 안전관리 인력 고용지원사업 참여기업 모집 공고",
    orgName: "울산경제일자리진흥원",
    category: "고용",
    region: "울산",
    targetBizTypes: ["제조"],
    amount: "안전관리 인력 고용 지원",
    deadline: "상시",
    description: "울산 자동차 부품업종의 안전관리 인력 고용을 지원하는 사업.",
    requirements: "울산 소재 자동차 부품 제조업체.",
    url: BIZINFO_DETAIL + "PBLN_000000000120388",
  },
  {
    id: "PBLN_000000000120308",
    title: "[경북] 안동시 2026년 중소기업 근로자 기숙사 임차비 지원사업",
    orgName: "경북경제진흥원",
    category: "인력",
    region: "경북",
    targetBizTypes: ["제조", "IT·소프트웨어", "서비스업"],
    amount: "기숙사 임차비 지원",
    deadline: "2026-04-24",
    description: "안동시 중소기업 근로자의 기숙사 임차비를 지원하여 인력 확보 및 정착 지원.",
    requirements: "안동시 소재 중소기업. 타 지역 출신 근로자 채용 기업.",
    url: BIZINFO_DETAIL + "PBLN_000000000120308",
  },

  // ──────── 기술 / R&D ────────
  {
    id: "PBLN_000000000120305",
    title: "[경북] 안동시 2026년 ICT·SW기업 지원사업",
    orgName: "경북경제진흥원",
    category: "기술",
    region: "경북",
    targetBizTypes: ["IT·소프트웨어"],
    amount: "ICT·SW 개발 지원",
    deadline: "2026-04-17",
    description: "안동시 소재 ICT·SW 기업의 기술 개발 및 사업화를 지원하는 사업.",
    requirements: "안동시 소재 ICT·SW 관련 기업.",
    url: BIZINFO_DETAIL + "PBLN_000000000120305",
  },
  {
    id: "PBLN_000000000120301",
    title: "2026년 딥테크 챌린지 프로젝트 기술도전형 제1차 기술수요조사",
    orgName: "중소기업기술정보진흥원",
    category: "기술",
    region: "전국",
    targetBizTypes: ["IT·소프트웨어", "제조"],
    amount: "기술개발 지원",
    deadline: "2026-05-04",
    description: "딥테크 분야 중소기업의 기술 도전을 지원하는 프로젝트. 난제 해결형 기술개발 지원.",
    requirements: "딥테크 분야 기술 역량 보유 중소기업.",
    url: BIZINFO_DETAIL + "PBLN_000000000120301",
  },
  {
    id: "PBLN_000000000120378",
    title: "2026년 1차 보건신기술(NET)인증기술 신청 및 인증기간 연장신청 접수 공고",
    orgName: "한국보건산업진흥원",
    category: "기술",
    region: "전국",
    targetBizTypes: ["제조", "IT·소프트웨어"],
    amount: "NET 인증",
    deadline: "2026-04-17",
    description: "보건 분야 신기술(NET) 인증 신청 접수. 인증 획득 시 공공조달 가점 등 혜택.",
    requirements: "보건 분야 신기술 보유 기업.",
    url: BIZINFO_DETAIL + "PBLN_000000000120378",
  },
  {
    id: "PBLN_000000000120336",
    title: "2026년 융복합 기술 오픈이노베이션 지원 참여기업 모집 공고",
    orgName: "한국농업기술진흥원",
    category: "기술",
    region: "전국",
    targetBizTypes: ["농림수산", "IT·소프트웨어", "제조"],
    amount: "오픈이노베이션 지원",
    deadline: "2026-04-24",
    description: "농식품 분야 융복합 기술의 오픈이노베이션을 지원. 기업 간 기술 협력 촉진.",
    requirements: "농식품 관련 융복합 기술 보유 기업.",
    url: BIZINFO_DETAIL + "PBLN_000000000120336",
  },

  // ──────── 콘텐츠 / 디자인 ────────
  {
    id: "PBLN_000000000120356",
    title: "[인천] 2026년 중소기업 디자인개발지원사업 (사용자경험중심 지원분야) 과제 모집 공고",
    orgName: "인천테크노파크",
    category: "경영",
    region: "인천",
    targetBizTypes: ["제조", "IT·소프트웨어", "서비스업"],
    amount: "디자인 개발비 지원",
    deadline: "2026-04-14",
    description: "인천 중소기업의 사용자 경험(UX) 중심 디자인 개발을 지원하는 사업.",
    requirements: "인천 소재 중소기업. 제품/서비스 디자인 개선이 필요한 기업.",
    url: BIZINFO_DETAIL + "PBLN_000000000120356",
  },
  {
    id: "PBLN_000000000120343",
    title: "2026년 부산 콘텐츠기업 엑셀러레이팅 운영 사업 참가기업 모집 공고",
    orgName: "부산정보산업진흥원",
    category: "경영",
    region: "부산",
    targetBizTypes: ["IT·소프트웨어", "서비스업"],
    amount: "엑셀러레이팅 프로그램 지원",
    deadline: "2026-04-20",
    description: "부산 소재 콘텐츠 기업의 성장을 위한 엑셀러레이팅 운영 사업. 멘토링, 네트워킹, 투자 연계.",
    requirements: "부산 소재 콘텐츠 관련 기업.",
    url: BIZINFO_DETAIL + "PBLN_000000000120343",
  },

  // ──────── IP / 지식재산 ────────
  {
    id: "PBLN_000000000120366",
    title: "[강원] 평창군 2026년 지식재산 첫걸음 지원사업",
    orgName: "강원특별자치도",
    category: "IP",
    region: "강원",
    targetBizTypes: ["제조", "IT·소프트웨어", "서비스업", "기타"],
    amount: "IP 출원 비용 지원",
    deadline: "2026-04-17",
    description: "평창군 소재 기업의 지식재산권(특허, 상표 등) 첫 출원을 지원하는 사업.",
    requirements: "평창군 소재 중소기업. 지식재산권 미보유 기업 우대.",
    url: BIZINFO_DETAIL + "PBLN_000000000120366",
  },
];
